name: Refresh Icons

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  refresh-icons:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and unzip file
        run: |
          wget -O icons.zip https://arch-center.azureedge.net/icons/Azure_Public_Service_Icons_V22.zip
          unzip -o icons.zip -d azure-icons
          rm icons.zip

      - name: Move SVG files
        run: |
          find azure-icons -type f -name "*.svg" -exec mv {} azure-icons \;
          

      - name: push-update
        run: |
          ls -R
          git config --global user.name 'Gitub Action Bot'
          git config --global user.email 'wilfried.woivre@users.noreply.github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am "Refresh Azure Icons"
          git pull --rebase
          git push
